version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: cakephp_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cakephp_php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html